# Generated by Django 5.2.8 on 2026-02-04 03:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0003_empresa_logo_empresa_razon_social_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FormTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=50, verbose_name='Código')),
                ('titulo', models.CharField(max_length=150, verbose_name='Título')),
                ('version', models.PositiveIntegerField(verbose_name='Versión')),
                ('activo', models.BooleanField(default=False, verbose_name='Activo')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
            ],
            options={
                'verbose_name': 'Plantilla de formulario',
                'verbose_name_plural': 'Plantillas de formularios',
                'db_table': 'forms_form_template',
                'ordering': ['codigo', '-version'],
                'unique_together': {('codigo', 'version')},
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=64, verbose_name='Clave')),
                ('etiqueta', models.CharField(max_length=255, verbose_name='Etiqueta')),
                ('tipo', models.CharField(choices=[('booleano', 'Booleano'), ('texto', 'Texto'), ('numero', 'Número'), ('seleccion', 'Selección'), ('multiseleccion', 'Multiselección'), ('fecha', 'Fecha'), ('archivo', 'Archivo')], max_length=20, verbose_name='Tipo')),
                ('requerido', models.BooleanField(default=False, verbose_name='Requerido')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('ayuda', models.TextField(blank=True, null=True, verbose_name='Ayuda')),
                ('reglas_visibilidad', models.JSONField(blank=True, default=dict, null=True, verbose_name='Reglas de visibilidad')),
                ('reglas_validacion', models.JSONField(blank=True, default=dict, null=True, verbose_name='Reglas de validación')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='forms.formtemplate', verbose_name='Plantilla')),
            ],
            options={
                'db_table': 'forms_question',
                'ordering': ['orden'],
                'unique_together': {('template', 'clave')},
            },
        ),
        migrations.CreateModel(
            name='FormRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('completado', 'Completado')], default='borrador', max_length=20, verbose_name='Estado')),
                ('scope_type', models.CharField(choices=[('extintor', 'Extintor'), ('area', 'Área'), ('site', 'Sitio')], max_length=20, verbose_name='Scope type')),
                ('scope_id', models.CharField(db_index=True, max_length=64, verbose_name='Scope ID')),
                ('tipo_servicio', models.CharField(blank=True, choices=[('levantamiento', 'Levantamiento'), ('mantenimiento', 'Mantenimiento'), ('recarga', 'Recarga'), ('venta', 'Venta'), ('inspeccion', 'Inspección')], max_length=30, null=True, verbose_name='Tipo de servicio')),
                ('respuestas_json', models.JSONField(blank=True, default=dict, verbose_name='Respuestas')),
                ('tiene_incidencias', models.BooleanField(default=False, verbose_name='Tiene incidencias')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='formularios', to='empresas.empresa', verbose_name='Empresa')),
                ('tecnico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='formularios', to=settings.AUTH_USER_MODEL, verbose_name='Técnico')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ejecuciones', to='forms.formtemplate', verbose_name='Plantilla')),
            ],
            options={
                'db_table': 'forms_form_run',
                'ordering': ['-creado_en'],
                'indexes': [models.Index(fields=['scope_type', 'scope_id'], name='forms_form__scope_t_102a2f_idx'), models.Index(fields=['template'], name='forms_form__templat_c6c451_idx'), models.Index(fields=['empresa'], name='forms_form__empresa_6464eb_idx'), models.Index(fields=['estado'], name='forms_form__estado_e68af7_idx'), models.Index(fields=['tiene_incidencias'], name='forms_form__tiene_i_74970f_idx'), models.Index(fields=['tipo_servicio'], name='forms_form__tipo_se_172c3f_idx')],
            },
        ),
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(max_length=100, verbose_name='Valor')),
                ('etiqueta', models.CharField(max_length=255, verbose_name='Etiqueta')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='forms.question', verbose_name='Pregunta')),
            ],
            options={
                'db_table': 'forms_question_option',
                'ordering': ['orden'],
                'unique_together': {('pregunta', 'valor')},
            },
        ),
    ]
