# Generated by Django 4.2.27 on 2026-01-10 05:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Extintor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código único del extintor (ej: EXT-001)', max_length=50, unique=True, verbose_name='Código')),
                ('ubicacion', models.CharField(help_text='Ubicación física del extintor', max_length=200, verbose_name='Ubicación')),
                ('tipo', models.CharField(choices=[('A', 'Clase A - Combustibles sólidos'), ('B', 'Clase B - Combustibles líquidos'), ('C', 'Clase C - Equipos eléctricos'), ('D', 'Clase D - Metales combustibles'), ('K', 'Clase K - Aceites y grasas de cocina'), ('ABC', 'Multipropósito ABC')], default='ABC', max_length=10, verbose_name='Tipo')),
                ('capacidad', models.CharField(help_text='Capacidad del extintor (ej: 10 kg, 6 L)', max_length=50, verbose_name='Capacidad')),
                ('fecha_fabricacion', models.DateField(blank=True, null=True, verbose_name='Fecha de Fabricación')),
                ('fecha_vencimiento', models.DateField(help_text='Fecha de vencimiento del extintor', verbose_name='Fecha de Vencimiento')),
                ('ultima_revision', models.DateField(blank=True, help_text='Fecha de la última revisión técnica', null=True, verbose_name='Última Revisión')),
                ('proxima_revision', models.DateField(help_text='Fecha programada para la próxima revisión', verbose_name='Próxima Revisión')),
                ('observaciones', models.TextField(blank=True, help_text='Notas adicionales sobre el extintor', verbose_name='Observaciones')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/', verbose_name='Código QR')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
            ],
            options={
                'verbose_name': 'Extintor',
                'verbose_name_plural': 'Extintores',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['codigo'], name='api_extinto_codigo_3203c0_idx'), models.Index(fields=['ubicacion'], name='api_extinto_ubicaci_b89264_idx'), models.Index(fields=['fecha_vencimiento'], name='api_extinto_fecha_v_8ad3a1_idx')],
            },
        ),
    ]
