# Generated by Django 4.2.27 on 2026-01-21 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extintor',
            name='tipo',
            field=models.CharField(choices=[('PQS_ABC', 'Polvo químico seco ABC'), ('PQS_BC', 'Polvo químico seco BC'), ('CO2', 'CO2'), ('AGUA', 'Agua'), ('ESPUMA', 'Espuma'), ('HALOTRON', 'Halotrón'), ('ACETATO_K', 'Acetato de potasio')], default='PQS_ABC', max_length=20, verbose_name='Agente Extintor'),
        ),
    ]
