# Generated by Django 4.2.27 on 2026-01-27 15:41

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extintor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código único del extintor (ej: EXT-001)', max_length=50, unique=True, verbose_name='Código')),
                ('ubicacion', models.CharField(help_text='Ubicación física del extintor', max_length=200, verbose_name='Ubicación')),
                ('tipo', models.CharField(choices=[('PQS_ABC', 'Polvo químico seco ABC'), ('PQS_BC', 'Polvo químico seco BC'), ('CO2', 'CO2'), ('AGUA', 'Agua'), ('ESPUMA', 'Espuma'), ('HALOTRON', 'Halotrón'), ('ACETATO_K', 'Acetato de potasio')], default='PQS_ABC', max_length=20, verbose_name='Agente Extintor')),
                ('capacidad', models.CharField(help_text='Capacidad del extintor (ej: 10 kg, 6 L)', max_length=50, verbose_name='Capacidad')),
                ('fecha_fabricacion', models.DateField(blank=True, null=True, verbose_name='Fecha de Fabricación')),
                ('fecha_vencimiento', models.DateField(help_text='Fecha de vencimiento del extintor', verbose_name='Fecha de Vencimiento')),
                ('ultima_revision', models.DateField(blank=True, help_text='Fecha de la última revisión técnica', null=True, verbose_name='Última Revisión')),
                ('proxima_revision', models.DateField(help_text='Fecha programada para la próxima revisión', verbose_name='Próxima Revisión')),
                ('observaciones', models.TextField(blank=True, help_text='Notas adicionales sobre el extintor', verbose_name='Observaciones')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/', verbose_name='Código QR')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='extintores', to='empresas.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Extintor',
                'verbose_name_plural': 'Extintores',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['codigo'], name='extintores__codigo_2e4be7_idx'), models.Index(fields=['ubicacion'], name='extintores__ubicaci_94f824_idx'), models.Index(fields=['fecha_vencimiento'], name='extintores__fecha_v_990c82_idx')],
            },
        ),
    ]
