# Generated by Django 4.2.27 on 2026-03-03 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extintores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='extintor',
            name='arena',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Arena contra incendios'),
        ),
    ]
