# Generated by Django 4.2.27 on 2026-03-03 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extintores', '0002_extintor_arena'),
    ]

    operations = [
        migrations.AddField(
            model_name='extintor',
            name='fecha_prueba_hidrostatica',
            field=models.DateField(help_text='Fecha de prueba hidrostatica', null=True, verbose_name='Fecha de prueba hidrostatica'),
        ),
    ]
