# Generated by Django 4.2.27 on 2026-03-07 03:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('extintores', '0003_extintor_fecha_prueba_hidrostatica'),
    ]

    operations = [
        migrations.AddField(
            model_name='extintor',
            name='creado_por',
            field=models.ForeignKey(blank=True, help_text='Usuario que registró el extintor', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extintores_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
    ]
