# Generated by Django 4.2.30 on 2026-05-21 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extintores', '0004_extintor_creado_por'),
    ]

    operations = [
        migrations.AddField(
            model_name='extintor',
            name='clase_fuego',
            field=models.CharField(blank=True, help_text='Clases de fuego que apaga el agente, separadas por coma. Ej: A,B,C', max_length=20, null=True, verbose_name='Clase de fuego'),
        ),
        migrations.AddField(
            model_name='extintor',
            name='modalidad',
            field=models.CharField(blank=True, choices=[('portatil', 'Portátil'), ('movil', 'Móvil')], max_length=20, null=True, verbose_name='Modalidad'),
        ),
        migrations.AlterField(
            model_name='extintor',
            name='tipo',
            field=models.CharField(choices=[('PQS_ABC', 'Polvo químico seco ABC'), ('CO2', 'CO2'), ('AGUA', 'Agua'), ('ESPUMA', 'Espuma'), ('ACETATO_K', 'Acetato de potasio'), ('COLD_FIRE', 'Cold Fire'), ('CLASE_D', 'Clase D - cloruro de sodio')], default='PQS_ABC', max_length=20, verbose_name='Agente Extintor'),
        ),
    ]
