# Generated by Django 4.2.27 on 2026-02-03 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        # No-op migration kept to preserve compatibility between branches.
        # Real field additions live in 0005_perfil_domicilio_perfil_telefono_and_more.
    ]
