# Generated by Django 5.2.8 on 2026-01-29 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_remove_nombre_completo'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='domicilio',
            field=models.CharField(blank=True, max_length=250, verbose_name='Domicilio'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='telefono',
            field=models.CharField(blank=True, max_length=30, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creaciÃ³n'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de actualizaciÃ³n'),
        ),
    ]
