# Generated by Django 4.2.27 on 2026-02-03 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        # No-op migration kept to preserve compatibility between branches.
        # Real field additions live in 0003_empresa_logo_empresa_razon_social_and_more.
    ]
