# Generated by Django 5.2.8 on 2026-01-29 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_alter_empresa_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='logo',
            field=models.ImageField(blank=True, help_text='Imagen del logo oficial para mostrar en reportes o etiquetas', null=True, upload_to='logos/', verbose_name='Logo'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='razon_social',
            field=models.CharField(blank=True, help_text='Razón social o razón legal de la empresa', max_length=200, verbose_name='Razón Social'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creaciÃ³n'),
        ),
    ]
