# Generated by Django 5.2.8 on 2026-02-05 01:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0003_empresa_logo_empresa_razon_social_and_more'),
        ('extintores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=180, verbose_name='Nombre del contacto')),
                ('cargo', models.CharField(max_length=150, verbose_name='Cargo')),
                ('correo_principal', models.EmailField(max_length=254, verbose_name='Correo principal')),
                ('correo_secundario', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo secundario')),
                ('telefono_principal', models.CharField(max_length=30, verbose_name='Teléfono principal')),
                ('telefono_secundario', models.CharField(blank=True, max_length=30, null=True, verbose_name='Teléfono secundario')),
                ('domicilio', models.CharField(max_length=250, verbose_name='Domicilio')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactos', to='empresas.empresa', verbose_name='Empresa')),
                ('extintor', models.ForeignKey(blank=True, help_text='Opcionalmente vincula un contacto con un extintor específico.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contactos', to='extintores.extintor', verbose_name='Extintor relacionado')),
            ],
            options={
                'verbose_name': 'Contacto',
                'verbose_name_plural': 'Contactos',
                'ordering': ['empresa__nombre', 'nombre'],
            },
        ),
    ]
