# Generated by Django 4.2.27 on 2026-03-07 03:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('empresas', '0006_contacto_inmueble'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='activa',
            field=models.BooleanField(default=True, verbose_name='Activa'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='cajones_estacionamiento',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Cajones de estacionamiento'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='creado_por',
            field=models.ForeignKey(blank=True, help_text='Usuario (técnico) que registró la empresa', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empresas_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='datos_quien_refiere',
            field=models.TextField(blank=True, help_text='Completar solo si no se encuentra en el establecimiento', verbose_name='Datos de quien refiere al cliente'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='en_establecimiento',
            field=models.BooleanField(default=True, help_text='Indica si el técnico está físicamente en el establecimiento', verbose_name='¿Se encuentra en el establecimiento?'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='fecha_evaluacion_riesgo',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de evaluación de riesgo'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='materiales_combustibles',
            field=models.TextField(blank=True, help_text='Describir los materiales combustibles presentes: sólidos (kg/ton), líquidos (litros), gases (capacidad), etc.', verbose_name='Materiales combustibles'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='metros_cuadrados_estacionamiento',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Metros cuadrados estacionamiento'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='metros_cuadrados_totales',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Metros cuadrados de todo el establecimiento', max_digits=10, null=True, verbose_name='Metros cuadrados totales'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='perimetro',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Perímetro del establecimiento en metros', max_digits=10, null=True, verbose_name='Perímetro'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='razon_social',
            field=models.CharField(blank=True, max_length=200, verbose_name='Razón Social'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='tipo_inmueble',
            field=models.CharField(blank=True, max_length=150, verbose_name='Tipo de inmueble'),
        ),
    ]
